version: '3'

services:
  # Frontend service configuration
  frontend:
    container_name: container-frontend
    build: ./Front
    ports:
      - 4200:4200
    working_dir: /app-frontend
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:9000
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:4200"]
      timeout: 10s
      retries: 5

  # Backend service configuration
  backend:
    container_name: container-backend
    build: ./Backend
    ports:
      - 9000:9000
    working_dir: /app-backend
environment:
  - APP_PORT=9000                     
  - JWT_SECRET=YourSuperSecretKey!   
  - MONGODB_URI=mongodb+srv://admin:admin@myCustomCluster.mongodb.net/myAppDB?retryWrites=true&w=majority 

healthcheck:
  test: ["CMD", "curl", "-f", "http://localhost:9000/health"]  # Vérifie l'état de l'application via l'endpoint /health
  interval: 30s               # Intervalle entre les vérifications de santé
  timeout: 5s                 # Durée maximale pour qu'un test réussisse
  retries: 3                  # Nombre de tentatives avant de déclarer une défaillance

