version: '3'

services:
  # Frontend service configuration
  frontend:
    container_name: container-frontend
    build: ./Front
    ports:
      - 4200:4200
    working_dir: /app-frontend
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:9000
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:4200"]
      timeout: 10s
      retries: 5

  # Backend service configuration
  backend:
    container_name: container-backend
    build: ./Backend
    ports:
      - 9000:9000
    working_dir: /app-backend
    environment: # Déplacez cette section ici, sous le service 'backend'
      - APP_PORT=9000                     
      - JWT_SECRET=YourSuperSecretKey!   
      - MONGODB_URI=mongodb+srv://admin:admin@myCustomCluster.mongodb.net/myAppDB?retryWrites=true&w=majority 
    healthcheck:  # Vérification de l'état de santé du service backend
      test: ["CMD", "curl", "-f", "http://localhost:9000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
